# This file was generated by stechec2-generator. DO NOT EDIT.

from enum import IntEnum
from typing import NamedTuple, List, Tuple  # noqa: F401

try:
    from _api import *
except ImportError:
    # If launched with the replay
    pass


# Vision du Voleur
VOLEUR_VISION_PORTEE = 5

# Déplacement du Voleur
VOLEUR_DEPLACEMENT = 10

# Vie du Voleur
VOLEUR_VIE = 10

# Attaque du voleur
VOLEUR_ATTAQUE = 5

# Cooldown de l'attaque "Palantir" du Voleur
VOLEUR_PALANTIR_CD = 3

# Cooldown de l'attaque "Traîtrise" du Voleur
VOLEUR_TRAITRISE_CD = 5

# Vision du Barbare
BARBARE_VISION_PORTEE = 4

# Déplacement du Barbare
BARBARE_DEPLACEMENT = 8

# Vie du Barbare
BARBARE_VIE = 10

# Attaque du Barbare
BARBARE_ATTAQUE = 3

# Cooldown de l'attaque "Bastoooon" du Barbare
BARBARE_BASTOOOON_CD = 3

# Portée de l'attaque "Bastoooon" du Barbare
BARBARE_BASTOOOON_PORTEE = 3

# Cooldown de l'attaque "Fus Ro Dah" du Barbare
BARBARE_FUS_RO_DAH_CD = 5

# Vision de l'Elfe
ELFE_VISION_PORTEE = 4

# Déplacement de l'Elfe
ELFE_DEPLACEMENT = 6

# Vie de l'Elfe
ELFE_VIE = 10

# Attaque de l'Elfe
ELFE_ATTAQUE = 2

# Cooldown de l'attaque "Loto, à qui le tour ?" de l'Elfe
ELFE_LOTO_CD = 5

# Cooldown de l'attaque "I See What You Did There" de l'Elfe
ELFE_I_SEE_CD = 5


# Type de personnage
class perso_classe(IntEnum):
    PERSO_VOLEUR = 0  # <- Voleur
    PERSO_BARBARE = 1  # <- Barbare
    PERSO_ELFE = 2  # <- Elfe


# Type de zone
class zone_type(IntEnum):
    ZONE_HERBE = 0  # <- Herbe
    ZONE_ROUTE = 1  # <- Route
    ZONE_FORET = 2  # <- Forêt
    ZONE_MARAIS = 3  # <- Marais
    ZONE_MUR = 4  # <- Mur
    ZONE_TOUR = 5  # <- Tour de guet
    ZONE_ERREUR = 6  # <- Erreur, case impossible


# Type d'attaque
class attaque_type(IntEnum):
    ATTAQUE_NORMALE = 0  # <- Attaque normale dont les dégats dépendent du personnage
    ATTAQUE_PALANTIR = 1  # <- Attaque 'Palantir' du Voleur
    ATTAQUE_TRAITRISE = 2  # <- Attaque 'Traîtrise' du Voleur
    ATTAQUE_BASTOOOON = 3  # <- Attaque 'Bastoooon' de du Barbare
    ATTAQUE_FUS_RO_DAH = 4  # <- Attaque 'Fus Ro Dah' du Barbare
    ATTAQUE_I_SEE = 5  # <- Attaque 'I see what you did there.' de l'Elfe
    ATTAQUE_LOTO = 6  # <- Attaque 'Loto, à qui le tour' de l'Elfe


# Orientation du personnage
class orientation(IntEnum):
    ORIENTATION_NORD = 0  # <- Orienté au nord
    ORIENTATION_EST = 1  # <- Orienté à l'est
    ORIENTATION_SUD = 2  # <- Orienté au sud
    ORIENTATION_OUEST = 3  # <- Orienté à l'ouest


# Erreurs possibles
class erreur(IntEnum):
    POSITION_IMPOSSIBLE = 0  # <- La position n'existe pas
    PERSONNAGE_IMPOSSIBLE = 1  # <- Le personnage n'existe pas ou ne vous appartient pas
    CHEMIN_IMPOSSIBLE = 2  # <- Le chemin est impossible
    ATTAQUE_INDISPONIBLE = 3  # <- L'attaque n'est pas utilisable pour le moment
    OK = 4  # <- Pas d'erreur


# Représente les informations sur un personnage
class perso_info(NamedTuple):
    equipe: int  # Équipe à laquelle appartient le personnage
    classe: perso_classe  # Classe du personnage
    vie: int  # Vie courante du personnage
    direction: orientation  # Orientation du personnage


